title: neko neko coin~
description: =.=

url: https://github.com/wlj459
baseurl: ""
BASE_PATH:/neko-neko-cion-
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 2

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html

social:
   github: wlj459
   email: wlj459@gmail.com

google_analytics: ""
